# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/romain/hashlink

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/romain/hashlink

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/opt/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/romain/hashlink/CMakeFiles /Users/romain/hashlink/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/romain/hashlink/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named fmt.hdll

# Build rule for target.
fmt.hdll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt.hdll
.PHONY : fmt.hdll

# fast build rule for target.
fmt.hdll/fast:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/build
.PHONY : fmt.hdll/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named sdl.hdll

# Build rule for target.
sdl.hdll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sdl.hdll
.PHONY : sdl.hdll

# fast build rule for target.
sdl.hdll/fast:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/build
.PHONY : sdl.hdll/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named hello.hl

# Build rule for target.
hello.hl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello.hl
.PHONY : hello.hl

# fast build rule for target.
hello.hl/fast:
	$(MAKE) -f CMakeFiles/hello.hl.dir/build.make CMakeFiles/hello.hl.dir/build
.PHONY : hello.hl/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named hl

# Build rule for target.
hl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hl
.PHONY : hl

# fast build rule for target.
hl/fast:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/build
.PHONY : hl/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named libhl

# Build rule for target.
libhl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libhl
.PHONY : libhl

# fast build rule for target.
libhl/fast:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/build
.PHONY : libhl/fast

include/pcre/pcre_chartables.o: include/pcre/pcre_chartables.c.o

.PHONY : include/pcre/pcre_chartables.o

# target to build an object file
include/pcre/pcre_chartables.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_chartables.c.o
.PHONY : include/pcre/pcre_chartables.c.o

include/pcre/pcre_chartables.i: include/pcre/pcre_chartables.c.i

.PHONY : include/pcre/pcre_chartables.i

# target to preprocess a source file
include/pcre/pcre_chartables.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_chartables.c.i
.PHONY : include/pcre/pcre_chartables.c.i

include/pcre/pcre_chartables.s: include/pcre/pcre_chartables.c.s

.PHONY : include/pcre/pcre_chartables.s

# target to generate assembly for a file
include/pcre/pcre_chartables.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_chartables.c.s
.PHONY : include/pcre/pcre_chartables.c.s

include/pcre/pcre_compile.o: include/pcre/pcre_compile.c.o

.PHONY : include/pcre/pcre_compile.o

# target to build an object file
include/pcre/pcre_compile.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_compile.c.o
.PHONY : include/pcre/pcre_compile.c.o

include/pcre/pcre_compile.i: include/pcre/pcre_compile.c.i

.PHONY : include/pcre/pcre_compile.i

# target to preprocess a source file
include/pcre/pcre_compile.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_compile.c.i
.PHONY : include/pcre/pcre_compile.c.i

include/pcre/pcre_compile.s: include/pcre/pcre_compile.c.s

.PHONY : include/pcre/pcre_compile.s

# target to generate assembly for a file
include/pcre/pcre_compile.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_compile.c.s
.PHONY : include/pcre/pcre_compile.c.s

include/pcre/pcre_dfa_exec.o: include/pcre/pcre_dfa_exec.c.o

.PHONY : include/pcre/pcre_dfa_exec.o

# target to build an object file
include/pcre/pcre_dfa_exec.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_dfa_exec.c.o
.PHONY : include/pcre/pcre_dfa_exec.c.o

include/pcre/pcre_dfa_exec.i: include/pcre/pcre_dfa_exec.c.i

.PHONY : include/pcre/pcre_dfa_exec.i

# target to preprocess a source file
include/pcre/pcre_dfa_exec.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_dfa_exec.c.i
.PHONY : include/pcre/pcre_dfa_exec.c.i

include/pcre/pcre_dfa_exec.s: include/pcre/pcre_dfa_exec.c.s

.PHONY : include/pcre/pcre_dfa_exec.s

# target to generate assembly for a file
include/pcre/pcre_dfa_exec.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_dfa_exec.c.s
.PHONY : include/pcre/pcre_dfa_exec.c.s

include/pcre/pcre_exec.o: include/pcre/pcre_exec.c.o

.PHONY : include/pcre/pcre_exec.o

# target to build an object file
include/pcre/pcre_exec.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_exec.c.o
.PHONY : include/pcre/pcre_exec.c.o

include/pcre/pcre_exec.i: include/pcre/pcre_exec.c.i

.PHONY : include/pcre/pcre_exec.i

# target to preprocess a source file
include/pcre/pcre_exec.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_exec.c.i
.PHONY : include/pcre/pcre_exec.c.i

include/pcre/pcre_exec.s: include/pcre/pcre_exec.c.s

.PHONY : include/pcre/pcre_exec.s

# target to generate assembly for a file
include/pcre/pcre_exec.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_exec.c.s
.PHONY : include/pcre/pcre_exec.c.s

include/pcre/pcre_fullinfo.o: include/pcre/pcre_fullinfo.c.o

.PHONY : include/pcre/pcre_fullinfo.o

# target to build an object file
include/pcre/pcre_fullinfo.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_fullinfo.c.o
.PHONY : include/pcre/pcre_fullinfo.c.o

include/pcre/pcre_fullinfo.i: include/pcre/pcre_fullinfo.c.i

.PHONY : include/pcre/pcre_fullinfo.i

# target to preprocess a source file
include/pcre/pcre_fullinfo.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_fullinfo.c.i
.PHONY : include/pcre/pcre_fullinfo.c.i

include/pcre/pcre_fullinfo.s: include/pcre/pcre_fullinfo.c.s

.PHONY : include/pcre/pcre_fullinfo.s

# target to generate assembly for a file
include/pcre/pcre_fullinfo.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_fullinfo.c.s
.PHONY : include/pcre/pcre_fullinfo.c.s

include/pcre/pcre_globals.o: include/pcre/pcre_globals.c.o

.PHONY : include/pcre/pcre_globals.o

# target to build an object file
include/pcre/pcre_globals.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_globals.c.o
.PHONY : include/pcre/pcre_globals.c.o

include/pcre/pcre_globals.i: include/pcre/pcre_globals.c.i

.PHONY : include/pcre/pcre_globals.i

# target to preprocess a source file
include/pcre/pcre_globals.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_globals.c.i
.PHONY : include/pcre/pcre_globals.c.i

include/pcre/pcre_globals.s: include/pcre/pcre_globals.c.s

.PHONY : include/pcre/pcre_globals.s

# target to generate assembly for a file
include/pcre/pcre_globals.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_globals.c.s
.PHONY : include/pcre/pcre_globals.c.s

include/pcre/pcre_newline.o: include/pcre/pcre_newline.c.o

.PHONY : include/pcre/pcre_newline.o

# target to build an object file
include/pcre/pcre_newline.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_newline.c.o
.PHONY : include/pcre/pcre_newline.c.o

include/pcre/pcre_newline.i: include/pcre/pcre_newline.c.i

.PHONY : include/pcre/pcre_newline.i

# target to preprocess a source file
include/pcre/pcre_newline.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_newline.c.i
.PHONY : include/pcre/pcre_newline.c.i

include/pcre/pcre_newline.s: include/pcre/pcre_newline.c.s

.PHONY : include/pcre/pcre_newline.s

# target to generate assembly for a file
include/pcre/pcre_newline.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_newline.c.s
.PHONY : include/pcre/pcre_newline.c.s

include/pcre/pcre_string_utils.o: include/pcre/pcre_string_utils.c.o

.PHONY : include/pcre/pcre_string_utils.o

# target to build an object file
include/pcre/pcre_string_utils.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_string_utils.c.o
.PHONY : include/pcre/pcre_string_utils.c.o

include/pcre/pcre_string_utils.i: include/pcre/pcre_string_utils.c.i

.PHONY : include/pcre/pcre_string_utils.i

# target to preprocess a source file
include/pcre/pcre_string_utils.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_string_utils.c.i
.PHONY : include/pcre/pcre_string_utils.c.i

include/pcre/pcre_string_utils.s: include/pcre/pcre_string_utils.c.s

.PHONY : include/pcre/pcre_string_utils.s

# target to generate assembly for a file
include/pcre/pcre_string_utils.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_string_utils.c.s
.PHONY : include/pcre/pcre_string_utils.c.s

include/pcre/pcre_tables.o: include/pcre/pcre_tables.c.o

.PHONY : include/pcre/pcre_tables.o

# target to build an object file
include/pcre/pcre_tables.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_tables.c.o
.PHONY : include/pcre/pcre_tables.c.o

include/pcre/pcre_tables.i: include/pcre/pcre_tables.c.i

.PHONY : include/pcre/pcre_tables.i

# target to preprocess a source file
include/pcre/pcre_tables.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_tables.c.i
.PHONY : include/pcre/pcre_tables.c.i

include/pcre/pcre_tables.s: include/pcre/pcre_tables.c.s

.PHONY : include/pcre/pcre_tables.s

# target to generate assembly for a file
include/pcre/pcre_tables.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_tables.c.s
.PHONY : include/pcre/pcre_tables.c.s

include/pcre/pcre_xclass.o: include/pcre/pcre_xclass.c.o

.PHONY : include/pcre/pcre_xclass.o

# target to build an object file
include/pcre/pcre_xclass.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_xclass.c.o
.PHONY : include/pcre/pcre_xclass.c.o

include/pcre/pcre_xclass.i: include/pcre/pcre_xclass.c.i

.PHONY : include/pcre/pcre_xclass.i

# target to preprocess a source file
include/pcre/pcre_xclass.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_xclass.c.i
.PHONY : include/pcre/pcre_xclass.c.i

include/pcre/pcre_xclass.s: include/pcre/pcre_xclass.c.s

.PHONY : include/pcre/pcre_xclass.s

# target to generate assembly for a file
include/pcre/pcre_xclass.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/include/pcre/pcre_xclass.c.s
.PHONY : include/pcre/pcre_xclass.c.s

libs/fmt/fmt.o: libs/fmt/fmt.c.o

.PHONY : libs/fmt/fmt.o

# target to build an object file
libs/fmt/fmt.c.o:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/fmt.c.o
.PHONY : libs/fmt/fmt.c.o

libs/fmt/fmt.i: libs/fmt/fmt.c.i

.PHONY : libs/fmt/fmt.i

# target to preprocess a source file
libs/fmt/fmt.c.i:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/fmt.c.i
.PHONY : libs/fmt/fmt.c.i

libs/fmt/fmt.s: libs/fmt/fmt.c.s

.PHONY : libs/fmt/fmt.s

# target to generate assembly for a file
libs/fmt/fmt.c.s:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/fmt.c.s
.PHONY : libs/fmt/fmt.c.s

libs/fmt/sha1.o: libs/fmt/sha1.c.o

.PHONY : libs/fmt/sha1.o

# target to build an object file
libs/fmt/sha1.c.o:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/sha1.c.o
.PHONY : libs/fmt/sha1.c.o

libs/fmt/sha1.i: libs/fmt/sha1.c.i

.PHONY : libs/fmt/sha1.i

# target to preprocess a source file
libs/fmt/sha1.c.i:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/sha1.c.i
.PHONY : libs/fmt/sha1.c.i

libs/fmt/sha1.s: libs/fmt/sha1.c.s

.PHONY : libs/fmt/sha1.s

# target to generate assembly for a file
libs/fmt/sha1.c.s:
	$(MAKE) -f CMakeFiles/fmt.hdll.dir/build.make CMakeFiles/fmt.hdll.dir/libs/fmt/sha1.c.s
.PHONY : libs/fmt/sha1.c.s

libs/sdl/gl.o: libs/sdl/gl.c.o

.PHONY : libs/sdl/gl.o

# target to build an object file
libs/sdl/gl.c.o:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/gl.c.o
.PHONY : libs/sdl/gl.c.o

libs/sdl/gl.i: libs/sdl/gl.c.i

.PHONY : libs/sdl/gl.i

# target to preprocess a source file
libs/sdl/gl.c.i:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/gl.c.i
.PHONY : libs/sdl/gl.c.i

libs/sdl/gl.s: libs/sdl/gl.c.s

.PHONY : libs/sdl/gl.s

# target to generate assembly for a file
libs/sdl/gl.c.s:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/gl.c.s
.PHONY : libs/sdl/gl.c.s

libs/sdl/sdl.o: libs/sdl/sdl.c.o

.PHONY : libs/sdl/sdl.o

# target to build an object file
libs/sdl/sdl.c.o:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/sdl.c.o
.PHONY : libs/sdl/sdl.c.o

libs/sdl/sdl.i: libs/sdl/sdl.c.i

.PHONY : libs/sdl/sdl.i

# target to preprocess a source file
libs/sdl/sdl.c.i:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/sdl.c.i
.PHONY : libs/sdl/sdl.c.i

libs/sdl/sdl.s: libs/sdl/sdl.c.s

.PHONY : libs/sdl/sdl.s

# target to generate assembly for a file
libs/sdl/sdl.c.s:
	$(MAKE) -f CMakeFiles/sdl.hdll.dir/build.make CMakeFiles/sdl.hdll.dir/libs/sdl/sdl.c.s
.PHONY : libs/sdl/sdl.c.s

src/alloc.o: src/alloc.c.o

.PHONY : src/alloc.o

# target to build an object file
src/alloc.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/alloc.c.o
.PHONY : src/alloc.c.o

src/alloc.i: src/alloc.c.i

.PHONY : src/alloc.i

# target to preprocess a source file
src/alloc.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/alloc.c.i
.PHONY : src/alloc.c.i

src/alloc.s: src/alloc.c.s

.PHONY : src/alloc.s

# target to generate assembly for a file
src/alloc.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/alloc.c.s
.PHONY : src/alloc.c.s

src/code.o: src/code.c.o

.PHONY : src/code.o

# target to build an object file
src/code.c.o:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/code.c.o
.PHONY : src/code.c.o

src/code.i: src/code.c.i

.PHONY : src/code.i

# target to preprocess a source file
src/code.c.i:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/code.c.i
.PHONY : src/code.c.i

src/code.s: src/code.c.s

.PHONY : src/code.s

# target to generate assembly for a file
src/code.c.s:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/code.c.s
.PHONY : src/code.c.s

src/debugger.o: src/debugger.c.o

.PHONY : src/debugger.o

# target to build an object file
src/debugger.c.o:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/debugger.c.o
.PHONY : src/debugger.c.o

src/debugger.i: src/debugger.c.i

.PHONY : src/debugger.i

# target to preprocess a source file
src/debugger.c.i:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/debugger.c.i
.PHONY : src/debugger.c.i

src/debugger.s: src/debugger.c.s

.PHONY : src/debugger.s

# target to generate assembly for a file
src/debugger.c.s:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/debugger.c.s
.PHONY : src/debugger.c.s

src/jit.o: src/jit.c.o

.PHONY : src/jit.o

# target to build an object file
src/jit.c.o:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/jit.c.o
.PHONY : src/jit.c.o

src/jit.i: src/jit.c.i

.PHONY : src/jit.i

# target to preprocess a source file
src/jit.c.i:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/jit.c.i
.PHONY : src/jit.c.i

src/jit.s: src/jit.c.s

.PHONY : src/jit.s

# target to generate assembly for a file
src/jit.c.s:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/jit.c.s
.PHONY : src/jit.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/main.c.s
.PHONY : src/main.c.s

src/module.o: src/module.c.o

.PHONY : src/module.o

# target to build an object file
src/module.c.o:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/module.c.o
.PHONY : src/module.c.o

src/module.i: src/module.c.i

.PHONY : src/module.i

# target to preprocess a source file
src/module.c.i:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/module.c.i
.PHONY : src/module.c.i

src/module.s: src/module.c.s

.PHONY : src/module.s

# target to generate assembly for a file
src/module.c.s:
	$(MAKE) -f CMakeFiles/hl.dir/build.make CMakeFiles/hl.dir/src/module.c.s
.PHONY : src/module.c.s

src/std/array.o: src/std/array.c.o

.PHONY : src/std/array.o

# target to build an object file
src/std/array.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/array.c.o
.PHONY : src/std/array.c.o

src/std/array.i: src/std/array.c.i

.PHONY : src/std/array.i

# target to preprocess a source file
src/std/array.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/array.c.i
.PHONY : src/std/array.c.i

src/std/array.s: src/std/array.c.s

.PHONY : src/std/array.s

# target to generate assembly for a file
src/std/array.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/array.c.s
.PHONY : src/std/array.c.s

src/std/buffer.o: src/std/buffer.c.o

.PHONY : src/std/buffer.o

# target to build an object file
src/std/buffer.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/buffer.c.o
.PHONY : src/std/buffer.c.o

src/std/buffer.i: src/std/buffer.c.i

.PHONY : src/std/buffer.i

# target to preprocess a source file
src/std/buffer.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/buffer.c.i
.PHONY : src/std/buffer.c.i

src/std/buffer.s: src/std/buffer.c.s

.PHONY : src/std/buffer.s

# target to generate assembly for a file
src/std/buffer.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/buffer.c.s
.PHONY : src/std/buffer.c.s

src/std/bytes.o: src/std/bytes.c.o

.PHONY : src/std/bytes.o

# target to build an object file
src/std/bytes.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/bytes.c.o
.PHONY : src/std/bytes.c.o

src/std/bytes.i: src/std/bytes.c.i

.PHONY : src/std/bytes.i

# target to preprocess a source file
src/std/bytes.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/bytes.c.i
.PHONY : src/std/bytes.c.i

src/std/bytes.s: src/std/bytes.c.s

.PHONY : src/std/bytes.s

# target to generate assembly for a file
src/std/bytes.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/bytes.c.s
.PHONY : src/std/bytes.c.s

src/std/cast.o: src/std/cast.c.o

.PHONY : src/std/cast.o

# target to build an object file
src/std/cast.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/cast.c.o
.PHONY : src/std/cast.c.o

src/std/cast.i: src/std/cast.c.i

.PHONY : src/std/cast.i

# target to preprocess a source file
src/std/cast.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/cast.c.i
.PHONY : src/std/cast.c.i

src/std/cast.s: src/std/cast.c.s

.PHONY : src/std/cast.s

# target to generate assembly for a file
src/std/cast.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/cast.c.s
.PHONY : src/std/cast.c.s

src/std/date.o: src/std/date.c.o

.PHONY : src/std/date.o

# target to build an object file
src/std/date.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/date.c.o
.PHONY : src/std/date.c.o

src/std/date.i: src/std/date.c.i

.PHONY : src/std/date.i

# target to preprocess a source file
src/std/date.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/date.c.i
.PHONY : src/std/date.c.i

src/std/date.s: src/std/date.c.s

.PHONY : src/std/date.s

# target to generate assembly for a file
src/std/date.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/date.c.s
.PHONY : src/std/date.c.s

src/std/error.o: src/std/error.c.o

.PHONY : src/std/error.o

# target to build an object file
src/std/error.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/error.c.o
.PHONY : src/std/error.c.o

src/std/error.i: src/std/error.c.i

.PHONY : src/std/error.i

# target to preprocess a source file
src/std/error.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/error.c.i
.PHONY : src/std/error.c.i

src/std/error.s: src/std/error.c.s

.PHONY : src/std/error.s

# target to generate assembly for a file
src/std/error.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/error.c.s
.PHONY : src/std/error.c.s

src/std/file.o: src/std/file.c.o

.PHONY : src/std/file.o

# target to build an object file
src/std/file.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/file.c.o
.PHONY : src/std/file.c.o

src/std/file.i: src/std/file.c.i

.PHONY : src/std/file.i

# target to preprocess a source file
src/std/file.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/file.c.i
.PHONY : src/std/file.c.i

src/std/file.s: src/std/file.c.s

.PHONY : src/std/file.s

# target to generate assembly for a file
src/std/file.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/file.c.s
.PHONY : src/std/file.c.s

src/std/fun.o: src/std/fun.c.o

.PHONY : src/std/fun.o

# target to build an object file
src/std/fun.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/fun.c.o
.PHONY : src/std/fun.c.o

src/std/fun.i: src/std/fun.c.i

.PHONY : src/std/fun.i

# target to preprocess a source file
src/std/fun.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/fun.c.i
.PHONY : src/std/fun.c.i

src/std/fun.s: src/std/fun.c.s

.PHONY : src/std/fun.s

# target to generate assembly for a file
src/std/fun.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/fun.c.s
.PHONY : src/std/fun.c.s

src/std/maps.o: src/std/maps.c.o

.PHONY : src/std/maps.o

# target to build an object file
src/std/maps.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/maps.c.o
.PHONY : src/std/maps.c.o

src/std/maps.i: src/std/maps.c.i

.PHONY : src/std/maps.i

# target to preprocess a source file
src/std/maps.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/maps.c.i
.PHONY : src/std/maps.c.i

src/std/maps.s: src/std/maps.c.s

.PHONY : src/std/maps.s

# target to generate assembly for a file
src/std/maps.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/maps.c.s
.PHONY : src/std/maps.c.s

src/std/math.o: src/std/math.c.o

.PHONY : src/std/math.o

# target to build an object file
src/std/math.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/math.c.o
.PHONY : src/std/math.c.o

src/std/math.i: src/std/math.c.i

.PHONY : src/std/math.i

# target to preprocess a source file
src/std/math.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/math.c.i
.PHONY : src/std/math.c.i

src/std/math.s: src/std/math.c.s

.PHONY : src/std/math.s

# target to generate assembly for a file
src/std/math.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/math.c.s
.PHONY : src/std/math.c.s

src/std/obj.o: src/std/obj.c.o

.PHONY : src/std/obj.o

# target to build an object file
src/std/obj.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/obj.c.o
.PHONY : src/std/obj.c.o

src/std/obj.i: src/std/obj.c.i

.PHONY : src/std/obj.i

# target to preprocess a source file
src/std/obj.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/obj.c.i
.PHONY : src/std/obj.c.i

src/std/obj.s: src/std/obj.c.s

.PHONY : src/std/obj.s

# target to generate assembly for a file
src/std/obj.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/obj.c.s
.PHONY : src/std/obj.c.s

src/std/process.o: src/std/process.c.o

.PHONY : src/std/process.o

# target to build an object file
src/std/process.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/process.c.o
.PHONY : src/std/process.c.o

src/std/process.i: src/std/process.c.i

.PHONY : src/std/process.i

# target to preprocess a source file
src/std/process.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/process.c.i
.PHONY : src/std/process.c.i

src/std/process.s: src/std/process.c.s

.PHONY : src/std/process.s

# target to generate assembly for a file
src/std/process.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/process.c.s
.PHONY : src/std/process.c.s

src/std/random.o: src/std/random.c.o

.PHONY : src/std/random.o

# target to build an object file
src/std/random.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/random.c.o
.PHONY : src/std/random.c.o

src/std/random.i: src/std/random.c.i

.PHONY : src/std/random.i

# target to preprocess a source file
src/std/random.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/random.c.i
.PHONY : src/std/random.c.i

src/std/random.s: src/std/random.c.s

.PHONY : src/std/random.s

# target to generate assembly for a file
src/std/random.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/random.c.s
.PHONY : src/std/random.c.s

src/std/regexp.o: src/std/regexp.c.o

.PHONY : src/std/regexp.o

# target to build an object file
src/std/regexp.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/regexp.c.o
.PHONY : src/std/regexp.c.o

src/std/regexp.i: src/std/regexp.c.i

.PHONY : src/std/regexp.i

# target to preprocess a source file
src/std/regexp.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/regexp.c.i
.PHONY : src/std/regexp.c.i

src/std/regexp.s: src/std/regexp.c.s

.PHONY : src/std/regexp.s

# target to generate assembly for a file
src/std/regexp.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/regexp.c.s
.PHONY : src/std/regexp.c.s

src/std/socket.o: src/std/socket.c.o

.PHONY : src/std/socket.o

# target to build an object file
src/std/socket.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/socket.c.o
.PHONY : src/std/socket.c.o

src/std/socket.i: src/std/socket.c.i

.PHONY : src/std/socket.i

# target to preprocess a source file
src/std/socket.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/socket.c.i
.PHONY : src/std/socket.c.i

src/std/socket.s: src/std/socket.c.s

.PHONY : src/std/socket.s

# target to generate assembly for a file
src/std/socket.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/socket.c.s
.PHONY : src/std/socket.c.s

src/std/string.o: src/std/string.c.o

.PHONY : src/std/string.o

# target to build an object file
src/std/string.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/string.c.o
.PHONY : src/std/string.c.o

src/std/string.i: src/std/string.c.i

.PHONY : src/std/string.i

# target to preprocess a source file
src/std/string.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/string.c.i
.PHONY : src/std/string.c.i

src/std/string.s: src/std/string.c.s

.PHONY : src/std/string.s

# target to generate assembly for a file
src/std/string.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/string.c.s
.PHONY : src/std/string.c.s

src/std/sys.o: src/std/sys.c.o

.PHONY : src/std/sys.o

# target to build an object file
src/std/sys.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys.c.o
.PHONY : src/std/sys.c.o

src/std/sys.i: src/std/sys.c.i

.PHONY : src/std/sys.i

# target to preprocess a source file
src/std/sys.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys.c.i
.PHONY : src/std/sys.c.i

src/std/sys.s: src/std/sys.c.s

.PHONY : src/std/sys.s

# target to generate assembly for a file
src/std/sys.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys.c.s
.PHONY : src/std/sys.c.s

src/std/sys_android.o: src/std/sys_android.c.o

.PHONY : src/std/sys_android.o

# target to build an object file
src/std/sys_android.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_android.c.o
.PHONY : src/std/sys_android.c.o

src/std/sys_android.i: src/std/sys_android.c.i

.PHONY : src/std/sys_android.i

# target to preprocess a source file
src/std/sys_android.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_android.c.i
.PHONY : src/std/sys_android.c.i

src/std/sys_android.s: src/std/sys_android.c.s

.PHONY : src/std/sys_android.s

# target to generate assembly for a file
src/std/sys_android.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_android.c.s
.PHONY : src/std/sys_android.c.s

src/std/sys_ios.o: src/std/sys_ios.m.o

.PHONY : src/std/sys_ios.o

# target to build an object file
src/std/sys_ios.m.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_ios.m.o
.PHONY : src/std/sys_ios.m.o

src/std/sys_ios.i: src/std/sys_ios.m.i

.PHONY : src/std/sys_ios.i

# target to preprocess a source file
src/std/sys_ios.m.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_ios.m.i
.PHONY : src/std/sys_ios.m.i

src/std/sys_ios.s: src/std/sys_ios.m.s

.PHONY : src/std/sys_ios.s

# target to generate assembly for a file
src/std/sys_ios.m.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/sys_ios.m.s
.PHONY : src/std/sys_ios.m.s

src/std/thread.o: src/std/thread.c.o

.PHONY : src/std/thread.o

# target to build an object file
src/std/thread.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/thread.c.o
.PHONY : src/std/thread.c.o

src/std/thread.i: src/std/thread.c.i

.PHONY : src/std/thread.i

# target to preprocess a source file
src/std/thread.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/thread.c.i
.PHONY : src/std/thread.c.i

src/std/thread.s: src/std/thread.c.s

.PHONY : src/std/thread.s

# target to generate assembly for a file
src/std/thread.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/thread.c.s
.PHONY : src/std/thread.c.s

src/std/types.o: src/std/types.c.o

.PHONY : src/std/types.o

# target to build an object file
src/std/types.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/types.c.o
.PHONY : src/std/types.c.o

src/std/types.i: src/std/types.c.i

.PHONY : src/std/types.i

# target to preprocess a source file
src/std/types.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/types.c.i
.PHONY : src/std/types.c.i

src/std/types.s: src/std/types.c.s

.PHONY : src/std/types.s

# target to generate assembly for a file
src/std/types.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/types.c.s
.PHONY : src/std/types.c.s

src/std/ucs2.o: src/std/ucs2.c.o

.PHONY : src/std/ucs2.o

# target to build an object file
src/std/ucs2.c.o:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/ucs2.c.o
.PHONY : src/std/ucs2.c.o

src/std/ucs2.i: src/std/ucs2.c.i

.PHONY : src/std/ucs2.i

# target to preprocess a source file
src/std/ucs2.c.i:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/ucs2.c.i
.PHONY : src/std/ucs2.c.i

src/std/ucs2.s: src/std/ucs2.c.s

.PHONY : src/std/ucs2.s

# target to generate assembly for a file
src/std/ucs2.c.s:
	$(MAKE) -f CMakeFiles/libhl.dir/build.make CMakeFiles/libhl.dir/src/std/ucs2.c.s
.PHONY : src/std/ucs2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousUpdate"
	@echo "... ContinuousStart"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... fmt.hdll"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... sdl.hdll"
	@echo "... edit_cache"
	@echo "... ContinuousConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyTest"
	@echo "... hello.hl"
	@echo "... Nightly"
	@echo "... hl"
	@echo "... NightlyStart"
	@echo "... libhl"
	@echo "... include/pcre/pcre_chartables.o"
	@echo "... include/pcre/pcre_chartables.i"
	@echo "... include/pcre/pcre_chartables.s"
	@echo "... include/pcre/pcre_compile.o"
	@echo "... include/pcre/pcre_compile.i"
	@echo "... include/pcre/pcre_compile.s"
	@echo "... include/pcre/pcre_dfa_exec.o"
	@echo "... include/pcre/pcre_dfa_exec.i"
	@echo "... include/pcre/pcre_dfa_exec.s"
	@echo "... include/pcre/pcre_exec.o"
	@echo "... include/pcre/pcre_exec.i"
	@echo "... include/pcre/pcre_exec.s"
	@echo "... include/pcre/pcre_fullinfo.o"
	@echo "... include/pcre/pcre_fullinfo.i"
	@echo "... include/pcre/pcre_fullinfo.s"
	@echo "... include/pcre/pcre_globals.o"
	@echo "... include/pcre/pcre_globals.i"
	@echo "... include/pcre/pcre_globals.s"
	@echo "... include/pcre/pcre_newline.o"
	@echo "... include/pcre/pcre_newline.i"
	@echo "... include/pcre/pcre_newline.s"
	@echo "... include/pcre/pcre_string_utils.o"
	@echo "... include/pcre/pcre_string_utils.i"
	@echo "... include/pcre/pcre_string_utils.s"
	@echo "... include/pcre/pcre_tables.o"
	@echo "... include/pcre/pcre_tables.i"
	@echo "... include/pcre/pcre_tables.s"
	@echo "... include/pcre/pcre_xclass.o"
	@echo "... include/pcre/pcre_xclass.i"
	@echo "... include/pcre/pcre_xclass.s"
	@echo "... libs/fmt/fmt.o"
	@echo "... libs/fmt/fmt.i"
	@echo "... libs/fmt/fmt.s"
	@echo "... libs/fmt/sha1.o"
	@echo "... libs/fmt/sha1.i"
	@echo "... libs/fmt/sha1.s"
	@echo "... libs/sdl/gl.o"
	@echo "... libs/sdl/gl.i"
	@echo "... libs/sdl/gl.s"
	@echo "... libs/sdl/sdl.o"
	@echo "... libs/sdl/sdl.i"
	@echo "... libs/sdl/sdl.s"
	@echo "... src/alloc.o"
	@echo "... src/alloc.i"
	@echo "... src/alloc.s"
	@echo "... src/code.o"
	@echo "... src/code.i"
	@echo "... src/code.s"
	@echo "... src/debugger.o"
	@echo "... src/debugger.i"
	@echo "... src/debugger.s"
	@echo "... src/jit.o"
	@echo "... src/jit.i"
	@echo "... src/jit.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/std/array.o"
	@echo "... src/std/array.i"
	@echo "... src/std/array.s"
	@echo "... src/std/buffer.o"
	@echo "... src/std/buffer.i"
	@echo "... src/std/buffer.s"
	@echo "... src/std/bytes.o"
	@echo "... src/std/bytes.i"
	@echo "... src/std/bytes.s"
	@echo "... src/std/cast.o"
	@echo "... src/std/cast.i"
	@echo "... src/std/cast.s"
	@echo "... src/std/date.o"
	@echo "... src/std/date.i"
	@echo "... src/std/date.s"
	@echo "... src/std/error.o"
	@echo "... src/std/error.i"
	@echo "... src/std/error.s"
	@echo "... src/std/file.o"
	@echo "... src/std/file.i"
	@echo "... src/std/file.s"
	@echo "... src/std/fun.o"
	@echo "... src/std/fun.i"
	@echo "... src/std/fun.s"
	@echo "... src/std/maps.o"
	@echo "... src/std/maps.i"
	@echo "... src/std/maps.s"
	@echo "... src/std/math.o"
	@echo "... src/std/math.i"
	@echo "... src/std/math.s"
	@echo "... src/std/obj.o"
	@echo "... src/std/obj.i"
	@echo "... src/std/obj.s"
	@echo "... src/std/process.o"
	@echo "... src/std/process.i"
	@echo "... src/std/process.s"
	@echo "... src/std/random.o"
	@echo "... src/std/random.i"
	@echo "... src/std/random.s"
	@echo "... src/std/regexp.o"
	@echo "... src/std/regexp.i"
	@echo "... src/std/regexp.s"
	@echo "... src/std/socket.o"
	@echo "... src/std/socket.i"
	@echo "... src/std/socket.s"
	@echo "... src/std/string.o"
	@echo "... src/std/string.i"
	@echo "... src/std/string.s"
	@echo "... src/std/sys.o"
	@echo "... src/std/sys.i"
	@echo "... src/std/sys.s"
	@echo "... src/std/sys_android.o"
	@echo "... src/std/sys_android.i"
	@echo "... src/std/sys_android.s"
	@echo "... src/std/sys_ios.o"
	@echo "... src/std/sys_ios.i"
	@echo "... src/std/sys_ios.s"
	@echo "... src/std/thread.o"
	@echo "... src/std/thread.i"
	@echo "... src/std/thread.s"
	@echo "... src/std/types.o"
	@echo "... src/std/types.i"
	@echo "... src/std/types.s"
	@echo "... src/std/ucs2.o"
	@echo "... src/std/ucs2.i"
	@echo "... src/std/ucs2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

